void	clearmsg(Msg*);
Msg*	readnet(void);
void	initnet(char*);
int	parsemsg(Msg*);
void	endmsg(Msg*);
int	sendmovenear(Munit*, Point, Munit*);
int	sendmove(Munit*, Point);
int	sendpause(void);
void	stepsnd(void);
void	initsnd(void);
void	linktomap(Munit*);
int	moveone(Point, Munit*, Munit*);
void	stepsim(void);
void	initsim(void);
void	initsv(int, char*);
void	flushcl(void);
void	packcl(char*, ...);
Msg*	getclbuf(void);
void	dopan(Point);
void	select(Point);
void	move(Point);
void	compose(int, int, u32int);
void	redraw(void);
void	updatefb(void);
void	resetfb(void);
void	drawfb(void);
void	initimg(void);
void	initfs(void);
void	setgoal(Point*, Munit*, Munit*);
Munit*	unitat(int, int);
int	isblocked(int, int, Unit*);
void	markmunit(Munit*, int);
int	findpath(Point, Munit*);
Munit*	mapspawn(int, int, Unit*);
void	initmap(void);
int	spawn(int, int, Unit*, int);
void	nukequeue(Pairheap**);
Pairheap*	popqueue(Pairheap**);
void	decreasekey(Pairheap*, double, Pairheap**);
void	pushqueue(Node*, Pairheap**);
int	lsb(uvlong);
int	msb(uvlong);
u64int*	baddr(int, int);
u64int*	rbaddr(int, int);
u64int*	bload(int, int, int, int, int, int, int, int);
void	bset(int, int, int, int, int);
void	initbmap(void);
void	dprint(char *, ...);
int	max(int, int);
int	min(int, int);
char*	estrdup(char*);
void*	erealloc(void*, ulong, ulong);
void*	emalloc(ulong);
vlong	flen(int);

#pragma	varargck	argpos	dprint	1
